export const mainColor = "#514EF6";
export const subMainColor = "#7593FF";
export const pointColor = "#F4F9FD"; // 면접 후기 등록할 때 포인트 있는 것
export const blueColor = "#6F828C";
export const grayTextColor = "#AFAFAF";
export const grayBorderColor = "#E3E4E3";
export const redColor = "#EC7575";
export const grayBackgroundColor = "#F5F5F5";
export const levelGrayColor = "#ECECEC";
export const mapBlueColor = "#7593FF";
